/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patient;

import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class BloodTestGUI extends javax.swing.JFrame {

    // this is importing the required classes
    private BloodTestScheduler scheduler;
    private ActionStack actionStack;
    private NoShowTracker noShowTracker;
    private Stack<Patient> undoStack;

    /**
     * Creates new form BloodTestGUI
     */
    public BloodTestGUI() {
        initComponents();
        scheduler = new BloodTestScheduler(); // Initialize the variables
        undoStack = new Stack<>();
        noShowTracker = new NoShowTracker();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBtn = new javax.swing.JButton();
        nameBlb = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        priorityLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        priorityTf = new javax.swing.JTextField();
        ageTf = new javax.swing.JTextField();
        gpTf = new javax.swing.JTextField();
        shoeqBtn = new javax.swing.JButton();
        noshowBtn = new javax.swing.JButton();
        undoBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextField();
        noshowqueueBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        nameBlb.setText("Name:");

        ageLbl.setText("Age:");

        priorityLbl.setText("Priority: (Urgent,Medium,Low)");

        jLabel4.setText("GP Details:");

        shoeqBtn.setText("Show-Queue");
        shoeqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoeqBtnActionPerformed(evt);
            }
        });

        noshowBtn.setText("Makr-No-Show");
        noshowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noshowBtnActionPerformed(evt);
            }
        });

        undoBtn.setText("Undo");
        undoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(textArea);

        noshowqueueBtn.setText("Last-No-Shows");
        noshowqueueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noshowqueueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameBlb)
                                .addComponent(priorityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(shoeqBtn)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gpTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priorityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noshowBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(undoBtn)))))
                .addGap(18, 18, 18)
                .addComponent(noshowqueueBtn)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameBlb)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priorityLbl)
                    .addComponent(priorityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageLbl)
                    .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(gpTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(shoeqBtn)
                    .addComponent(noshowBtn)
                    .addComponent(undoBtn)
                    .addComponent(noshowqueueBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try {
            String name = nameTf.getText();
            String priority = priorityTf.getText().toLowerCase();
            int age = Integer.parseInt(ageTf.getText());
            String gpDetails = gpTf.getText();
            boolean fromHospital = priority.equals("urgent");

            // Create new patient and add to queue
            Patient newPatient = new Patient(name, priority, gpDetails, age, fromHospital);
            scheduler.enqueue(newPatient);
            undoStack.push(newPatient); // Store for undo

            // Display in text area
            textArea.setText("Added: " + newPatient.toString() + "\n");

            // Clear input fields
            nameTf.setText("");
            priorityTf.setText("");
            ageTf.setText("");
            gpTf.setText("");

        } catch (NumberFormatException e) {// this is the error message 
            JOptionPane.showMessageDialog(this, "Invalid Age! Please enter a number.");
        }

    }//GEN-LAST:event_addBtnActionPerformed

    private void shoeqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoeqBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText("Current Queue:\n" + scheduler.displayQueue());
       /** textArea.setText(""); // tryed to get it to print on a new line but couldnt
            String queueDisplay = "Current Queue:\n";

                for (Patient patient : scheduler.getQueue()) {
                queueDisplay += patient.toString() + "\n";
            }

             textArea.setText(queueDisplay); 
        */ 
    }//GEN-LAST:event_shoeqBtnActionPerformed

    private void noshowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noshowBtnActionPerformed
        // TODO add your handling code here:
        if (!scheduler.isEmpty()) {
            Patient missedPatient = scheduler.dequeue();
            noShowTracker.addNoShow(missedPatient);
            textArea.setText("No Show: " + missedPatient.toString() + "\n");
            undoStack.push(missedPatient);
        } else {
            textArea.setText("No patients in queue.\n");
        }
    }//GEN-LAST:event_noshowBtnActionPerformed

    private void undoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBtnActionPerformed
        // TODO add your handling code here:
        if (!undoStack.isEmpty()) {
            Patient lastAction = undoStack.pop();
            scheduler.enqueue(lastAction);
            textArea.setText("Undo: Restored " + lastAction.getName() + "\n");
        } else {
            JOptionPane.showMessageDialog(this, "Nothing to undo.");
        }
    }//GEN-LAST:event_undoBtnActionPerformed

    private void noshowqueueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noshowqueueBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(noShowTracker.displayNoShows());
    }//GEN-LAST:event_noshowqueueBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodTestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTf;
    private javax.swing.JTextField gpTf;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameBlb;
    private javax.swing.JTextField nameTf;
    private javax.swing.JButton noshowBtn;
    private javax.swing.JButton noshowqueueBtn;
    private javax.swing.JLabel priorityLbl;
    private javax.swing.JTextField priorityTf;
    private javax.swing.JButton shoeqBtn;
    private javax.swing.JTextField textArea;
    private javax.swing.JButton undoBtn;
    // End of variables declaration//GEN-END:variables
}
